### ISSUE TITLE
Atualizar a página de sobre

### ISSUE THREAD

**Issue by allythy** [grupyrn/blog#13]

**Comment by jhonatacaiob** [comment]
@itepifanio @allythy Eu gostaria de pegar essa tarefa. O que eu preciso para fazer ela?

**Comment by itepifanio** [comment]
@jhonatacaiob que ótimo!

A gente não tem uma ideia bem definida, tirar o lorem ipsum atual por algo que conte um pouco sobre a atuação do GruPy-RN acredito que já seja suficiente. Talvez seja legal adicionar a missão da comunidade "Promover um espaço inclusivo, acolhedor, sem intimidação e que fomente a troca de conhecimentos e a inovação por meio da linguagem de programação Python". Fique a vontade para usar a sua criatividade!

Você pode tirar algumas informações do nosso plano de patrocínio: https://drive.google.com/file/d/1zna1VPdUgUfEDzw41S0ZDgJ_6Fd8llr0/view?usp=sharing

**Comment by jhonatacaiob** [comment]
@itepifanio Fiz um textinho e alterei a rota para `/sobre` .

Estou a disposição para fazer qualquer  mudança que for sugerida

https://github.com/grupyrn/blog/pull/25

**Comment by itepifanio** [comment]
@jhonatacaiob muito obrigado, ficou ótimo. Acho que depois vamos selecionar algumas fotos pra colocar junto com o sobre, mas vou aceitando e fechando o PR desde já!
